replicaCount: 1

image:
  repository: daneln2003/home_assignment_elementor
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

tolerations: []
affinity: {}
nodeSelector: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: rickmorty.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
